// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUKMntVHFqAUzMgu4pZXmlOy5nnEMo_oQ',
    appId: '1:212137490442:web:530f8f4ce7816bd40ac7f3',
    messagingSenderId: '212137490442',
    projectId: 'event-planning-44df6',
    authDomain: 'event-planning-44df6.firebaseapp.com',
    storageBucket: 'event-planning-44df6.firebasestorage.app',
    measurementId: 'G-JTS10YL520',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLntgbINSiEVlOVoOxXLQwMKgFmWZlVRo',
    appId: '1:212137490442:android:49ac0052896231fe0ac7f3',
    messagingSenderId: '212137490442',
    projectId: 'event-planning-44df6',
    storageBucket: 'event-planning-44df6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2R94BwmiJfkX6K008Tq8oOyX19MAb06Y',
    appId: '1:212137490442:ios:23ee44464f75c8b20ac7f3',
    messagingSenderId: '212137490442',
    projectId: 'event-planning-44df6',
    storageBucket: 'event-planning-44df6.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2R94BwmiJfkX6K008Tq8oOyX19MAb06Y',
    appId: '1:212137490442:ios:23ee44464f75c8b20ac7f3',
    messagingSenderId: '212137490442',
    projectId: 'event-planning-44df6',
    storageBucket: 'event-planning-44df6.firebasestorage.app',
    iosBundleId: 'com.example.eventPlanning',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUKMntVHFqAUzMgu4pZXmlOy5nnEMo_oQ',
    appId: '1:212137490442:web:0e95681a7c26f9990ac7f3',
    messagingSenderId: '212137490442',
    projectId: 'event-planning-44df6',
    authDomain: 'event-planning-44df6.firebaseapp.com',
    storageBucket: 'event-planning-44df6.firebasestorage.app',
    measurementId: 'G-R9GJ58RBDG',
  );
}
